const theme = require("tailwindcss/defaultTheme");
//import Path from "./src/assets/Path.svg";
module.exports = {
    purge: ["./src/**/*.{jsx,tsx,js,ts}", "./public/index.html"],
    darkMode: false, // or 'media' or 'class'
    theme: {
        fontFamily: {
            sans: ["Nexa"],
            regular: ["Nexa-Regular"],
            nexabold: ["Nexa-Bold"],
            nexablack: ["Nexa-Black"],
            book: ["Nexa-Book"],
            cunia: ["Cunia"],
            cuniaRegular: ["Cunia-Regular"]
        },
        textColor: {
            primary: "#fd3a55",
            primaryLight: "#6F97FF",
            primaryNormal: "#4037B3",
            coolGray: "#8493A8",
            midGray: "#ADB9CA",
            lightGray: "#CAD3DF",
            deepBlue: "#0E0E52",
            brightYellow: "#FFC13D",
            lilac: "#95B4FF",
            green: "#007527",
            EB5757: "#EB5757",
            DEE8FF: "#DEE8FF",
            EFEEFB: "#EFEEFB",
            D7D4F5: "#D7D4F5",
            B9B6EC: "#B9B6EC",
            white: "#ffffff",
            C6D7FF: "#C6D7FF",
            F5F8FF: "#F5F8FF",
            blue: "#4054b2",
            lightPink: "#D02F68",
            black: "#000000",
            Brown: "#654321",
            darkGray: "#696969",

        },
        extend: {
            height: {
                module: "calc(100vh - 8rem)",
                320: "320px",
            },

            width: {
                module: "calc(100% - 4rem)",
                sideline: "87%",
                card: "340px",
                580: "580px",
            },
            fontSize: {
                9: "9px",
                10: "10px",
                11: "11px",
                12: "12px",
                13: "13px",
                14: "14px",
                15: "15px",
                16: "16px",
                17: "17px",
                18: "18px",
                19: "19px",
                20: "20px",
                21: "21px",
                22: "22px",
                23: "23px",
                24: "24px",
                25: "25px",
                26: "26px",
                27: "27px",
                28: "28px",
                29: "29px",
                30: "30px",
                70: "70px",
                31: "31px",
                32: "32px",
                33: "33px",
                34: "34px",
                35: "35px",
                36: "36px",
                37: "37px",
                38: "38px",
                39: "39px",
                40: "40px",
                54: "54px",
                68: "68px",
            },
            lineHeight: {
                10: "10px",
                11: "11px",
                12: "12px",
                13: "13px",
                14: "14px",
                15: "15px",
                16: "16px",
                17: "17px",
                18: "18px",
                19: "19px",
                20: "20px",
                21: "21px",
                22: "22px",
                23: "23px",
                24: "24px",
                25: "25px",
                26: "26px",
                27: "27px",
                28: "28px",
                29: "29px",
                30: "30px",
                31: "31px",
                32: "32px",
                33: "33px",
                34: "34px",
                35: "35px",
                36: "36px",
                37: "37px",
                38: "38px",
                39: "39px",
                40: "40px",
            },
            colors: {
                primary: "#fd3a55",
                primaryLight: "#6F97FF",
                primaryNormal: "#4037B3",
                coolGray: "#8493A8",
                midGray: "#ADB9CA",
                lightGray: "#CAD3DF",
                deepBlue: "#18288D",
                brightYellow: "#FFC13D",
                lilac: "#95B4FF",
                indigo: "#4169e1",
                darkBlue: "#1167b1",
                EB5757: "#EB5757",
                DEE8FF: "#DEE8FF",
                EFEEFB: "#EFEEFB",
                D7D4F5: "#D7D4F5",
                B9B6EC: "#B9B6EC",
                white: "#ffffff",
                C6D7FF: "#C6D7FF",
                F5F8FF: "#F5F8FF",
                BG1364A3: "#1364A3",
                C4c4c4c: "#4c4c4c",
                green: "#23A455",
                lightPink: "#D02F68",
                semiBlack: "#252424",
                darkGray: "#4E4E4E",
                bgWhite: "#f8f8ff",
                bgBlue: "#0e0e52",
                DFEFFF: "#DFEFFF",
                E61A89: "#E61A89",
                Gold: "#B4833E",
                lightGold: "#EDD87D",
                Platinum: "#C7C6C4",
                lightPlatinum: "#F4F3F1",
                Brown: "#925F36",

            },
            outline: {
                gray: {
                    400: "#CBCBCB",
                },
            },
            spacing: {
                3.5: "0.875rem",
                7.5: "1.875rem",
            },
            zIndex: {
                1: "1",
            },
            minHeight: {
                ...theme.spacing,
            },
            borderWidth: {
                12: "12px",
                1: "1px",
            },
        },
    },
    variants: {
        extend: {
            margin: ["last"],
            backgroundColor: ["odd", "even"],
        },
    },
    plugins: [],
};